### PR TITLE
config: added ava prefix

### PR DESCRIPTION
**Pull request by solcik**
This pull request is fixing:

```
1:1  error  Definition for rule 'no-identical-title' was not found                                    no-identical-title
1:1  error  Definition for rule 'no-invalid-end' was not found                                        no-invalid-end
1:1  error  Definition for rule 'no-only-test' was not found                                          no-only-test
1:1  error  Definition for rule 'no-skip-assert' was not found                                        no-skip-assert
1:1  error  Definition for rule 'no-skip-test' was not found                                          no-skip-test
1:1  error  Definition for rule 'test-ended' was not found                                            test-ended
1:1  error  Definition for rule 'test-title' was not found                                            test-title
```

### CODE REVIEW

**Comment by sindresorhus** [comment]
According to the docs this is not correct: http://eslint.org/docs/developer-guide/working-with-plugins#rules-in-plugins

You're the one that has to prefix rules with `ava/`, not this plugin.

**Comment by jfmengels** [comment]
@sindresorhus The error happens with the recommended settings.
I can replicate the error when using `"extends": "plugin:ava/recommended"` in my eslintrc.

**Comment by erikdesjardins** [comment]
@sindresorhus That's true, but this PR changes the recommended config, not the rules themselves.

See also the recommended configs of [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/8222cdd5e2e9ecd4536b01eed74984dc44691849/config/errors.js), [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/blob/a3eccd8b30d867660e5fe9506c6ebf6862ff3b6f/index.js#L47-L67).

**Comment by jfmengels** [comment]
I can replicate this, and this fix makes it ok, so this looks good to me. Thanks @solcik!

**Comment by sindresorhus** [comment]
Oh, sorry. I thought I was looking at a different part of that file.

**Pull request merged**
