### PR TITLE
Add plenty of rules (#2, #3, #5, #6, #7 and #8)

### PR DESCRIPTION
**Pull request by jfmengels**
I implemented the rules in issues #2, #3, #5, #6, #7 and #8.

I'm not that familiar with Ava (but pretty excited about it, so I felt pretty motivated to do this), so let me     know if I've got anything wrong, if there's anything to fix, or if you prefer this being split into multiple PRs.

Also, if someone can tell me why the use of `const` makes the tests fail in Node 0.10/0.12 but is ok on master where I also see `const`...

### CODE REVIEW

**Comment by sindresorhus** [comment]
Oh wow. This is amazing!

celebration

> or if you prefer this being split into multiple PRs

Yes, please. That would make it a lot easier to review and easier for you to update :)

> Also, if someone can tell me why the use of const makes the tests fail in Node 0.10/0.12 but is ok on master where I also see const...

AVA transpiles the test files with Babel, but not the code itself. So you can only use `const` in the test files.

**Comment by jfmengels** [comment]
> AVA transpiles the test files with Babel, but not the code itself. So you can only use const in the test files

Gotcha!

> "or if you prefer this being split into multiple PRs"
> Yes, please. That would make it a lot easier to review and easier for you to update :)

Ok. Will split it up later today then. I hope there won't be too many conflicts as some of them touch the same portions (util, index and README), but I'll handle that if it comes up.

> Oh wow. This is amazing!

Glad you like it ;)

**Comment by vdemedes** [comment]
Thanks for an amazing contribution, @jfmengels!

giphy 6

**Comment by sindresorhus** [comment]
Lol. So much Leonardo :p

**Comment by jfmengels** [comment]
(couldn't resist)

I'll close this one, I've opened a few others (#13, #14, #15), feel free to merge however you feel, I'll come around to handle conflicts). I'll create the rest of them when those get merged, as some use code that has been added in those PRs (`util.js`) and merging them before will smooth things IMO.

**Comment by sindresorhus** [comment]
Yes, good idea, was going to mention that. Better to handle some of them first.

**Pull request closed without merging**
