### PR TITLE
Allow `t.plan()` in the `use-t-well` rule

### LINKED ISSUE #80: Shouldn't `plan` be allowed by `use-t-well`?
Is there a reason `plan` is not one of the [whitelisted methods](https://github.com/sindresorhus/eslint-plugin-ava/pull/73/files#diff-4fb9820698995f93e7be653c378e5b20R5)?

Discovered via
```
Unknown assertion method `plan`  ava/use-t-well
```
Followup to #73

### PR DESCRIPTION
**Pull request by wenzowski**
closes #80

### CODE REVIEW

**Comment by jfmengels** [comment]
Thanks for the PR!

Do you mind adding a test case for it? To make sure it doesn't break later.

**Comment by wenzowski** [comment]
No prob, just have to actually check out the repo...

**Comment by wenzowski** [comment]
Added. Can squash and tweak commit messages if desired.

**Comment by jfmengels** [comment]
Cool! Thanks a lot @wenzowski 

LGTM, but I'll let someone else take a look before merging

> Can squash and tweak commit messages if desired.

That's not needed, thanks. GitHub now has a button to squash commits and merge, so we'll use that.

**Comment by sindresorhus** [comment]
Thanks for the fix @wenzowski :)

**Pull request merged**
