### PR TITLE
doc: add French translations links

### PR DESCRIPTION
**Pull request by forresst**

### CODE REVIEW

**Comment by jfmengels** [comment]
Cool! :D

Should we create the link to french every time we create a new rule, in the hope that the translation comes quickly? Or should we wait for a PR to come, or simply be notified that it exists?

**Comment by sindresorhus** [comment]
Wait for a PR. It's annoying for users to click a link that doesn't exists.

**Comment by sindresorhus** [comment]
Woot. @forresst is awesome!

**Comment by forresst** [comment]
I try to translate asap, but it is possible that I can not do it quickly.

>Wait for a PR. It's annoying for users to click a link that doesn't exists.

I agree, it's like this for repository AVA

**Pull request merged**
