### PR TITLE
add max-asserts rule (fixes #6)

### LINKED ISSUE #6: `max-asserts` rule
Limit the amount of assertions per test to enforce people to split up large tests into smaller ones. Should accept a number of assertions.

### PR DESCRIPTION
**Pull request by jfmengels**
add max-asserts rule (fixes #6) :)

Last one of the rules implemented in #11 :)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Omg. Can't believe how fast those rules got done. Thank you so much @jfmengels! 🍻

Would you be interested in becoming a maintainer on this repo? No commitment required, just some credit in the readme.

unicorn12

**Comment by jfmengels** [comment]
Would love to! It would be the first repo I'm a maintainer of too :)

I'll probably look at implementing other rules and proposing other ones (I think there are a lot of rules that can be made for in-editor purposes, like #26). Thanks for the amazing cooperation on all these PRs :)

**Comment by sindresorhus** [comment]
> Thanks for the amazing cooperation on all these PRs :)

No, thank you.

**Comment by vdemedes** [comment]
Damn @jfmengels is spitting fire! Super cool job!

**Pull request merged**
